.\" Process this file with `groff -man -Tascii zoe.1`
.TH ZOE 1
.SH NAME
zoe \- a programming language
.SH SYNOPSYS
.B zoe [OPTION]... [SCRIPT [ARGS]...]
.SH DESCRIPTION
.B zoe
is a programming language that is productive, fun to use, and feels familiar to
the experienced programmer. A complete reference to the language is present in
the file
.I doc/zoe.html.
.SH OPTIONS
.IP -v, --version
show version and exit
.IP -h, --help
show help and exit
.SH AUTHOR
André Wagner <andre.nho@gmail.com>
